

OPENING = 'OPENING'
CLOSING = 'CLOSING'

LATE_INIT = 'LATE_INIT'

PIPELINE_READY = 'PIPELINE_READY'

BROADCASTER_JOINED = 'BROADCASTER_JOINED'

HEIGHT_UPDATE = 'HEIGHT_UPDATE'
WIDTH_UPDATE = 'WIDTH_UPDATE'

KEYPRESS = 'KEYPRESS'